/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByCityDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByCityDataAttributes{}

// DataByCityDataAttributes struct for DataByCityDataAttributes
type DataByCityDataAttributes struct {
	// City name
	Name string `json:"name"`
	// City location
	Locations string `json:"locations"`
	Streets []DataByCityDataAttributesStreetsInner `json:"streets"`
}

type _DataByCityDataAttributes DataByCityDataAttributes

// NewDataByCityDataAttributes instantiates a new DataByCityDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByCityDataAttributes(name string, locations string, streets []DataByCityDataAttributesStreetsInner) *DataByCityDataAttributes {
	this := DataByCityDataAttributes{}
	this.Name = name
	this.Locations = locations
	this.Streets = streets
	return &this
}

// NewDataByCityDataAttributesWithDefaults instantiates a new DataByCityDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByCityDataAttributesWithDefaults() *DataByCityDataAttributes {
	this := DataByCityDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *DataByCityDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataByCityDataAttributes) SetName(v string) {
	o.Name = v
}

// GetLocations returns the Locations field value
func (o *DataByCityDataAttributes) GetLocations() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributes) GetLocationsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locations, true
}

// SetLocations sets field value
func (o *DataByCityDataAttributes) SetLocations(v string) {
	o.Locations = v
}

// GetStreets returns the Streets field value
func (o *DataByCityDataAttributes) GetStreets() []DataByCityDataAttributesStreetsInner {
	if o == nil {
		var ret []DataByCityDataAttributesStreetsInner
		return ret
	}

	return o.Streets
}

// GetStreetsOk returns a tuple with the Streets field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributes) GetStreetsOk() ([]DataByCityDataAttributesStreetsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Streets, true
}

// SetStreets sets field value
func (o *DataByCityDataAttributes) SetStreets(v []DataByCityDataAttributesStreetsInner) {
	o.Streets = v
}

func (o DataByCityDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByCityDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["locations"] = o.Locations
	toSerialize["streets"] = o.Streets
	return toSerialize, nil
}

func (o *DataByCityDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"locations",
		"streets",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByCityDataAttributes := _DataByCityDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByCityDataAttributes)

	if err != nil {
		return err
	}

	*o = DataByCityDataAttributes(varDataByCityDataAttributes)

	return err
}

type NullableDataByCityDataAttributes struct {
	value *DataByCityDataAttributes
	isSet bool
}

func (v NullableDataByCityDataAttributes) Get() *DataByCityDataAttributes {
	return v.value
}

func (v *NullableDataByCityDataAttributes) Set(val *DataByCityDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByCityDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByCityDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByCityDataAttributes(val *DataByCityDataAttributes) *NullableDataByCityDataAttributes {
	return &NullableDataByCityDataAttributes{value: val, isSet: true}
}

func (v NullableDataByCityDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByCityDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


