/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateStreet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStreet{}

// CreateStreet struct for CreateStreet
type CreateStreet struct {
	Data CreateStreetData `json:"data"`
}

type _CreateStreet CreateStreet

// NewCreateStreet instantiates a new CreateStreet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStreet(data CreateStreetData) *CreateStreet {
	this := CreateStreet{}
	this.Data = data
	return &this
}

// NewCreateStreetWithDefaults instantiates a new CreateStreet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStreetWithDefaults() *CreateStreet {
	this := CreateStreet{}
	return &this
}

// GetData returns the Data field value
func (o *CreateStreet) GetData() CreateStreetData {
	if o == nil {
		var ret CreateStreetData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateStreet) GetDataOk() (*CreateStreetData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateStreet) SetData(v CreateStreetData) {
	o.Data = v
}

func (o CreateStreet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStreet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateStreet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateStreet := _CreateStreet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateStreet)

	if err != nil {
		return err
	}

	*o = CreateStreet(varCreateStreet)

	return err
}

type NullableCreateStreet struct {
	value *CreateStreet
	isSet bool
}

func (v NullableCreateStreet) Get() *CreateStreet {
	return v.value
}

func (v *NullableCreateStreet) Set(val *CreateStreet) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStreet) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStreet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStreet(val *CreateStreet) *NullableCreateStreet {
	return &NullableCreateStreet{value: val, isSet: true}
}

func (v NullableCreateStreet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStreet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


