/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDistrictData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistrictData{}

// UpdateDistrictData struct for UpdateDistrictData
type UpdateDistrictData struct {
	Type string `json:"type"`
	Attributes UpdateDistrictDataAttributes `json:"attributes"`
}

type _UpdateDistrictData UpdateDistrictData

// NewUpdateDistrictData instantiates a new UpdateDistrictData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistrictData(type_ string, attributes UpdateDistrictDataAttributes) *UpdateDistrictData {
	this := UpdateDistrictData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateDistrictDataWithDefaults instantiates a new UpdateDistrictData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistrictDataWithDefaults() *UpdateDistrictData {
	this := UpdateDistrictData{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateDistrictData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateDistrictData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateDistrictData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateDistrictData) GetAttributes() UpdateDistrictDataAttributes {
	if o == nil {
		var ret UpdateDistrictDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateDistrictData) GetAttributesOk() (*UpdateDistrictDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateDistrictData) SetAttributes(v UpdateDistrictDataAttributes) {
	o.Attributes = v
}

func (o UpdateDistrictData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistrictData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateDistrictData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDistrictData := _UpdateDistrictData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDistrictData)

	if err != nil {
		return err
	}

	*o = UpdateDistrictData(varUpdateDistrictData)

	return err
}

type NullableUpdateDistrictData struct {
	value *UpdateDistrictData
	isSet bool
}

func (v NullableUpdateDistrictData) Get() *UpdateDistrictData {
	return v.value
}

func (v *NullableUpdateDistrictData) Set(val *UpdateDistrictData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistrictData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistrictData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistrictData(val *UpdateDistrictData) *NullableUpdateDistrictData {
	return &NullableUpdateDistrictData{value: val, isSet: true}
}

func (v NullableUpdateDistrictData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistrictData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


