/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCityDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCityDataAttributes{}

// CreateCityDataAttributes struct for CreateCityDataAttributes
type CreateCityDataAttributes struct {
	// City name
	Name string `json:"name"`
	// City location
	Location string `json:"location"`
}

type _CreateCityDataAttributes CreateCityDataAttributes

// NewCreateCityDataAttributes instantiates a new CreateCityDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCityDataAttributes(name string, location string) *CreateCityDataAttributes {
	this := CreateCityDataAttributes{}
	this.Name = name
	this.Location = location
	return &this
}

// NewCreateCityDataAttributesWithDefaults instantiates a new CreateCityDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCityDataAttributesWithDefaults() *CreateCityDataAttributes {
	this := CreateCityDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCityDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCityDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCityDataAttributes) SetName(v string) {
	o.Name = v
}

// GetLocation returns the Location field value
func (o *CreateCityDataAttributes) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *CreateCityDataAttributes) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *CreateCityDataAttributes) SetLocation(v string) {
	o.Location = v
}

func (o CreateCityDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCityDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["location"] = o.Location
	return toSerialize, nil
}

func (o *CreateCityDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCityDataAttributes := _CreateCityDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCityDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateCityDataAttributes(varCreateCityDataAttributes)

	return err
}

type NullableCreateCityDataAttributes struct {
	value *CreateCityDataAttributes
	isSet bool
}

func (v NullableCreateCityDataAttributes) Get() *CreateCityDataAttributes {
	return v.value
}

func (v *NullableCreateCityDataAttributes) Set(val *CreateCityDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCityDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCityDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCityDataAttributes(val *CreateCityDataAttributes) *NullableCreateCityDataAttributes {
	return &NullableCreateCityDataAttributes{value: val, isSet: true}
}

func (v NullableCreateCityDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCityDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


