/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCityData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityData{}

// UpdateCityData struct for UpdateCityData
type UpdateCityData struct {
	Type string `json:"type"`
	Attributes UpdateCityDataAttributes `json:"attributes"`
}

type _UpdateCityData UpdateCityData

// NewUpdateCityData instantiates a new UpdateCityData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityData(type_ string, attributes UpdateCityDataAttributes) *UpdateCityData {
	this := UpdateCityData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCityDataWithDefaults instantiates a new UpdateCityData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityDataWithDefaults() *UpdateCityData {
	this := UpdateCityData{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateCityData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCityData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCityData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCityData) GetAttributes() UpdateCityDataAttributes {
	if o == nil {
		var ret UpdateCityDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCityData) GetAttributesOk() (*UpdateCityDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCityData) SetAttributes(v UpdateCityDataAttributes) {
	o.Attributes = v
}

func (o UpdateCityData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCityData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCityData := _UpdateCityData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCityData)

	if err != nil {
		return err
	}

	*o = UpdateCityData(varUpdateCityData)

	return err
}

type NullableUpdateCityData struct {
	value *UpdateCityData
	isSet bool
}

func (v NullableUpdateCityData) Get() *UpdateCityData {
	return v.value
}

func (v *NullableUpdateCityData) Set(val *UpdateCityData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityData(val *UpdateCityData) *NullableUpdateCityData {
	return &NullableUpdateCityData{value: val, isSet: true}
}

func (v NullableUpdateCityData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


