/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCityDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCityDataAttributes{}

// CreateCityDataAttributes struct for CreateCityDataAttributes
type CreateCityDataAttributes struct {
	// City name
	Name string `json:"name"`
	// City uuid
	CityId string `json:"city_id"`
	// Country uuid if u need to change country for the city
	CountryId *string `json:"country_id,omitempty"`
}

type _CreateCityDataAttributes CreateCityDataAttributes

// NewCreateCityDataAttributes instantiates a new CreateCityDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCityDataAttributes(name string, cityId string) *CreateCityDataAttributes {
	this := CreateCityDataAttributes{}
	this.Name = name
	this.CityId = cityId
	return &this
}

// NewCreateCityDataAttributesWithDefaults instantiates a new CreateCityDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCityDataAttributesWithDefaults() *CreateCityDataAttributes {
	this := CreateCityDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateCityDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCityDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCityDataAttributes) SetName(v string) {
	o.Name = v
}

// GetCityId returns the CityId field value
func (o *CreateCityDataAttributes) GetCityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value
// and a boolean to check if the value has been set.
func (o *CreateCityDataAttributes) GetCityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CityId, true
}

// SetCityId sets field value
func (o *CreateCityDataAttributes) SetCityId(v string) {
	o.CityId = v
}

// GetCountryId returns the CountryId field value if set, zero value otherwise.
func (o *CreateCityDataAttributes) GetCountryId() string {
	if o == nil || IsNil(o.CountryId) {
		var ret string
		return ret
	}
	return *o.CountryId
}

// GetCountryIdOk returns a tuple with the CountryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCityDataAttributes) GetCountryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CountryId) {
		return nil, false
	}
	return o.CountryId, true
}

// HasCountryId returns a boolean if a field has been set.
func (o *CreateCityDataAttributes) HasCountryId() bool {
	if o != nil && !IsNil(o.CountryId) {
		return true
	}

	return false
}

// SetCountryId gets a reference to the given string and assigns it to the CountryId field.
func (o *CreateCityDataAttributes) SetCountryId(v string) {
	o.CountryId = &v
}

func (o CreateCityDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCityDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["city_id"] = o.CityId
	if !IsNil(o.CountryId) {
		toSerialize["country_id"] = o.CountryId
	}
	return toSerialize, nil
}

func (o *CreateCityDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"city_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCityDataAttributes := _CreateCityDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCityDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateCityDataAttributes(varCreateCityDataAttributes)

	return err
}

type NullableCreateCityDataAttributes struct {
	value *CreateCityDataAttributes
	isSet bool
}

func (v NullableCreateCityDataAttributes) Get() *CreateCityDataAttributes {
	return v.value
}

func (v *NullableCreateCityDataAttributes) Set(val *CreateCityDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCityDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCityDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCityDataAttributes(val *CreateCityDataAttributes) *NullableCreateCityDataAttributes {
	return &NullableCreateCityDataAttributes{value: val, isSet: true}
}

func (v NullableCreateCityDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCityDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


