/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistrictDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistrictDataAttributes{}

// CreateDistrictDataAttributes struct for CreateDistrictDataAttributes
type CreateDistrictDataAttributes struct {
	// District name
	Name string `json:"name"`
	// city uuid
	CityId string `json:"city_id"`
}

type _CreateDistrictDataAttributes CreateDistrictDataAttributes

// NewCreateDistrictDataAttributes instantiates a new CreateDistrictDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistrictDataAttributes(name string, cityId string) *CreateDistrictDataAttributes {
	this := CreateDistrictDataAttributes{}
	this.Name = name
	this.CityId = cityId
	return &this
}

// NewCreateDistrictDataAttributesWithDefaults instantiates a new CreateDistrictDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistrictDataAttributesWithDefaults() *CreateDistrictDataAttributes {
	this := CreateDistrictDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateDistrictDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDistrictDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDistrictDataAttributes) SetName(v string) {
	o.Name = v
}

// GetCityId returns the CityId field value
func (o *CreateDistrictDataAttributes) GetCityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value
// and a boolean to check if the value has been set.
func (o *CreateDistrictDataAttributes) GetCityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CityId, true
}

// SetCityId sets field value
func (o *CreateDistrictDataAttributes) SetCityId(v string) {
	o.CityId = v
}

func (o CreateDistrictDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistrictDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["city_id"] = o.CityId
	return toSerialize, nil
}

func (o *CreateDistrictDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"city_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistrictDataAttributes := _CreateDistrictDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistrictDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateDistrictDataAttributes(varCreateDistrictDataAttributes)

	return err
}

type NullableCreateDistrictDataAttributes struct {
	value *CreateDistrictDataAttributes
	isSet bool
}

func (v NullableCreateDistrictDataAttributes) Get() *CreateDistrictDataAttributes {
	return v.value
}

func (v *NullableCreateDistrictDataAttributes) Set(val *CreateDistrictDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistrictDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistrictDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistrictDataAttributes(val *CreateDistrictDataAttributes) *NullableCreateDistrictDataAttributes {
	return &NullableCreateDistrictDataAttributes{value: val, isSet: true}
}

func (v NullableCreateDistrictDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistrictDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


