/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateStreetDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStreetDataAttributes{}

// CreateStreetDataAttributes struct for CreateStreetDataAttributes
type CreateStreetDataAttributes struct {
	// District name
	Name string `json:"name"`
	// District uuid
	DistrictId string `json:"district_id"`
}

type _CreateStreetDataAttributes CreateStreetDataAttributes

// NewCreateStreetDataAttributes instantiates a new CreateStreetDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStreetDataAttributes(name string, districtId string) *CreateStreetDataAttributes {
	this := CreateStreetDataAttributes{}
	this.Name = name
	this.DistrictId = districtId
	return &this
}

// NewCreateStreetDataAttributesWithDefaults instantiates a new CreateStreetDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStreetDataAttributesWithDefaults() *CreateStreetDataAttributes {
	this := CreateStreetDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *CreateStreetDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateStreetDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateStreetDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDistrictId returns the DistrictId field value
func (o *CreateStreetDataAttributes) GetDistrictId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DistrictId
}

// GetDistrictIdOk returns a tuple with the DistrictId field value
// and a boolean to check if the value has been set.
func (o *CreateStreetDataAttributes) GetDistrictIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistrictId, true
}

// SetDistrictId sets field value
func (o *CreateStreetDataAttributes) SetDistrictId(v string) {
	o.DistrictId = v
}

func (o CreateStreetDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStreetDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["district_id"] = o.DistrictId
	return toSerialize, nil
}

func (o *CreateStreetDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"district_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateStreetDataAttributes := _CreateStreetDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateStreetDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateStreetDataAttributes(varCreateStreetDataAttributes)

	return err
}

type NullableCreateStreetDataAttributes struct {
	value *CreateStreetDataAttributes
	isSet bool
}

func (v NullableCreateStreetDataAttributes) Get() *CreateStreetDataAttributes {
	return v.value
}

func (v *NullableCreateStreetDataAttributes) Set(val *CreateStreetDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStreetDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStreetDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStreetDataAttributes(val *CreateStreetDataAttributes) *NullableCreateStreetDataAttributes {
	return &NullableCreateStreetDataAttributes{value: val, isSet: true}
}

func (v NullableCreateStreetDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStreetDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


