/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByCityDataAttributesStreetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByCityDataAttributesStreetsInner{}

// DataByCityDataAttributesStreetsInner struct for DataByCityDataAttributesStreetsInner
type DataByCityDataAttributesStreetsInner struct {
	// street id
	Id string `json:"id"`
	// street name
	Name string `json:"name"`
	// street location
	Locations string `json:"locations"`
}

type _DataByCityDataAttributesStreetsInner DataByCityDataAttributesStreetsInner

// NewDataByCityDataAttributesStreetsInner instantiates a new DataByCityDataAttributesStreetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByCityDataAttributesStreetsInner(id string, name string, locations string) *DataByCityDataAttributesStreetsInner {
	this := DataByCityDataAttributesStreetsInner{}
	this.Id = id
	this.Name = name
	this.Locations = locations
	return &this
}

// NewDataByCityDataAttributesStreetsInnerWithDefaults instantiates a new DataByCityDataAttributesStreetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByCityDataAttributesStreetsInnerWithDefaults() *DataByCityDataAttributesStreetsInner {
	this := DataByCityDataAttributesStreetsInner{}
	return &this
}

// GetId returns the Id field value
func (o *DataByCityDataAttributesStreetsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributesStreetsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataByCityDataAttributesStreetsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataByCityDataAttributesStreetsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributesStreetsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataByCityDataAttributesStreetsInner) SetName(v string) {
	o.Name = v
}

// GetLocations returns the Locations field value
func (o *DataByCityDataAttributesStreetsInner) GetLocations() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributesStreetsInner) GetLocationsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locations, true
}

// SetLocations sets field value
func (o *DataByCityDataAttributesStreetsInner) SetLocations(v string) {
	o.Locations = v
}

func (o DataByCityDataAttributesStreetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByCityDataAttributesStreetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["locations"] = o.Locations
	return toSerialize, nil
}

func (o *DataByCityDataAttributesStreetsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"locations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByCityDataAttributesStreetsInner := _DataByCityDataAttributesStreetsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByCityDataAttributesStreetsInner)

	if err != nil {
		return err
	}

	*o = DataByCityDataAttributesStreetsInner(varDataByCityDataAttributesStreetsInner)

	return err
}

type NullableDataByCityDataAttributesStreetsInner struct {
	value *DataByCityDataAttributesStreetsInner
	isSet bool
}

func (v NullableDataByCityDataAttributesStreetsInner) Get() *DataByCityDataAttributesStreetsInner {
	return v.value
}

func (v *NullableDataByCityDataAttributesStreetsInner) Set(val *DataByCityDataAttributesStreetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByCityDataAttributesStreetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByCityDataAttributesStreetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByCityDataAttributesStreetsInner(val *DataByCityDataAttributesStreetsInner) *NullableDataByCityDataAttributesStreetsInner {
	return &NullableDataByCityDataAttributesStreetsInner{value: val, isSet: true}
}

func (v NullableDataByCityDataAttributesStreetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByCityDataAttributesStreetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


