/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistrictData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistrictData{}

// CreateDistrictData struct for CreateDistrictData
type CreateDistrictData struct {
	Type string `json:"type"`
	Attributes CreateDistrictDataAttributes `json:"attributes"`
}

type _CreateDistrictData CreateDistrictData

// NewCreateDistrictData instantiates a new CreateDistrictData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistrictData(type_ string, attributes CreateDistrictDataAttributes) *CreateDistrictData {
	this := CreateDistrictData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateDistrictDataWithDefaults instantiates a new CreateDistrictData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistrictDataWithDefaults() *CreateDistrictData {
	this := CreateDistrictData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateDistrictData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDistrictData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDistrictData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateDistrictData) GetAttributes() CreateDistrictDataAttributes {
	if o == nil {
		var ret CreateDistrictDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateDistrictData) GetAttributesOk() (*CreateDistrictDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateDistrictData) SetAttributes(v CreateDistrictDataAttributes) {
	o.Attributes = v
}

func (o CreateDistrictData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistrictData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateDistrictData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistrictData := _CreateDistrictData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistrictData)

	if err != nil {
		return err
	}

	*o = CreateDistrictData(varCreateDistrictData)

	return err
}

type NullableCreateDistrictData struct {
	value *CreateDistrictData
	isSet bool
}

func (v NullableCreateDistrictData) Get() *CreateDistrictData {
	return v.value
}

func (v *NullableCreateDistrictData) Set(val *CreateDistrictData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistrictData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistrictData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistrictData(val *CreateDistrictData) *NullableCreateDistrictData {
	return &NullableCreateDistrictData{value: val, isSet: true}
}

func (v NullableCreateDistrictData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistrictData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


