/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCity{}

// CreateCity struct for CreateCity
type CreateCity struct {
	Data CreateCityData `json:"data"`
}

type _CreateCity CreateCity

// NewCreateCity instantiates a new CreateCity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCity(data CreateCityData) *CreateCity {
	this := CreateCity{}
	this.Data = data
	return &this
}

// NewCreateCityWithDefaults instantiates a new CreateCity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCityWithDefaults() *CreateCity {
	this := CreateCity{}
	return &this
}

// GetData returns the Data field value
func (o *CreateCity) GetData() CreateCityData {
	if o == nil {
		var ret CreateCityData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateCity) GetDataOk() (*CreateCityData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateCity) SetData(v CreateCityData) {
	o.Data = v
}

func (o CreateCity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateCity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCity := _CreateCity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCity)

	if err != nil {
		return err
	}

	*o = CreateCity(varCreateCity)

	return err
}

type NullableCreateCity struct {
	value *CreateCity
	isSet bool
}

func (v NullableCreateCity) Get() *CreateCity {
	return v.value
}

func (v *NullableCreateCity) Set(val *CreateCity) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCity) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCity(val *CreateCity) *NullableCreateCity {
	return &NullableCreateCity{value: val, isSet: true}
}

func (v NullableCreateCity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


