/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByDistrictDataAttributesStreetsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByDistrictDataAttributesStreetsInner{}

// DataByDistrictDataAttributesStreetsInner struct for DataByDistrictDataAttributesStreetsInner
type DataByDistrictDataAttributesStreetsInner struct {
	// street id
	Id string `json:"id"`
	// street name
	Name string `json:"name"`
}

type _DataByDistrictDataAttributesStreetsInner DataByDistrictDataAttributesStreetsInner

// NewDataByDistrictDataAttributesStreetsInner instantiates a new DataByDistrictDataAttributesStreetsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByDistrictDataAttributesStreetsInner(id string, name string) *DataByDistrictDataAttributesStreetsInner {
	this := DataByDistrictDataAttributesStreetsInner{}
	this.Id = id
	this.Name = name
	return &this
}

// NewDataByDistrictDataAttributesStreetsInnerWithDefaults instantiates a new DataByDistrictDataAttributesStreetsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByDistrictDataAttributesStreetsInnerWithDefaults() *DataByDistrictDataAttributesStreetsInner {
	this := DataByDistrictDataAttributesStreetsInner{}
	return &this
}

// GetId returns the Id field value
func (o *DataByDistrictDataAttributesStreetsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataByDistrictDataAttributesStreetsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataByDistrictDataAttributesStreetsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataByDistrictDataAttributesStreetsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataByDistrictDataAttributesStreetsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataByDistrictDataAttributesStreetsInner) SetName(v string) {
	o.Name = v
}

func (o DataByDistrictDataAttributesStreetsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByDistrictDataAttributesStreetsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *DataByDistrictDataAttributesStreetsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByDistrictDataAttributesStreetsInner := _DataByDistrictDataAttributesStreetsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByDistrictDataAttributesStreetsInner)

	if err != nil {
		return err
	}

	*o = DataByDistrictDataAttributesStreetsInner(varDataByDistrictDataAttributesStreetsInner)

	return err
}

type NullableDataByDistrictDataAttributesStreetsInner struct {
	value *DataByDistrictDataAttributesStreetsInner
	isSet bool
}

func (v NullableDataByDistrictDataAttributesStreetsInner) Get() *DataByDistrictDataAttributesStreetsInner {
	return v.value
}

func (v *NullableDataByDistrictDataAttributesStreetsInner) Set(val *DataByDistrictDataAttributesStreetsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByDistrictDataAttributesStreetsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByDistrictDataAttributesStreetsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByDistrictDataAttributesStreetsInner(val *DataByDistrictDataAttributesStreetsInner) *NullableDataByDistrictDataAttributesStreetsInner {
	return &NullableDataByDistrictDataAttributesStreetsInner{value: val, isSet: true}
}

func (v NullableDataByDistrictDataAttributesStreetsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByDistrictDataAttributesStreetsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


