/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateStreetDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStreetDataAttributes{}

// UpdateStreetDataAttributes struct for UpdateStreetDataAttributes
type UpdateStreetDataAttributes struct {
	// City name
	NewName *string `json:"new_name,omitempty"`
	// City location
	NewLocation *string `json:"new_location,omitempty"`
	// City uuid
	NewCity *string `json:"new_city,omitempty"`
}

// NewUpdateStreetDataAttributes instantiates a new UpdateStreetDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStreetDataAttributes() *UpdateStreetDataAttributes {
	this := UpdateStreetDataAttributes{}
	return &this
}

// NewUpdateStreetDataAttributesWithDefaults instantiates a new UpdateStreetDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStreetDataAttributesWithDefaults() *UpdateStreetDataAttributes {
	this := UpdateStreetDataAttributes{}
	return &this
}

// GetNewName returns the NewName field value if set, zero value otherwise.
func (o *UpdateStreetDataAttributes) GetNewName() string {
	if o == nil || IsNil(o.NewName) {
		var ret string
		return ret
	}
	return *o.NewName
}

// GetNewNameOk returns a tuple with the NewName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreetDataAttributes) GetNewNameOk() (*string, bool) {
	if o == nil || IsNil(o.NewName) {
		return nil, false
	}
	return o.NewName, true
}

// HasNewName returns a boolean if a field has been set.
func (o *UpdateStreetDataAttributes) HasNewName() bool {
	if o != nil && !IsNil(o.NewName) {
		return true
	}

	return false
}

// SetNewName gets a reference to the given string and assigns it to the NewName field.
func (o *UpdateStreetDataAttributes) SetNewName(v string) {
	o.NewName = &v
}

// GetNewLocation returns the NewLocation field value if set, zero value otherwise.
func (o *UpdateStreetDataAttributes) GetNewLocation() string {
	if o == nil || IsNil(o.NewLocation) {
		var ret string
		return ret
	}
	return *o.NewLocation
}

// GetNewLocationOk returns a tuple with the NewLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreetDataAttributes) GetNewLocationOk() (*string, bool) {
	if o == nil || IsNil(o.NewLocation) {
		return nil, false
	}
	return o.NewLocation, true
}

// HasNewLocation returns a boolean if a field has been set.
func (o *UpdateStreetDataAttributes) HasNewLocation() bool {
	if o != nil && !IsNil(o.NewLocation) {
		return true
	}

	return false
}

// SetNewLocation gets a reference to the given string and assigns it to the NewLocation field.
func (o *UpdateStreetDataAttributes) SetNewLocation(v string) {
	o.NewLocation = &v
}

// GetNewCity returns the NewCity field value if set, zero value otherwise.
func (o *UpdateStreetDataAttributes) GetNewCity() string {
	if o == nil || IsNil(o.NewCity) {
		var ret string
		return ret
	}
	return *o.NewCity
}

// GetNewCityOk returns a tuple with the NewCity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateStreetDataAttributes) GetNewCityOk() (*string, bool) {
	if o == nil || IsNil(o.NewCity) {
		return nil, false
	}
	return o.NewCity, true
}

// HasNewCity returns a boolean if a field has been set.
func (o *UpdateStreetDataAttributes) HasNewCity() bool {
	if o != nil && !IsNil(o.NewCity) {
		return true
	}

	return false
}

// SetNewCity gets a reference to the given string and assigns it to the NewCity field.
func (o *UpdateStreetDataAttributes) SetNewCity(v string) {
	o.NewCity = &v
}

func (o UpdateStreetDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStreetDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NewName) {
		toSerialize["new_name"] = o.NewName
	}
	if !IsNil(o.NewLocation) {
		toSerialize["new_location"] = o.NewLocation
	}
	if !IsNil(o.NewCity) {
		toSerialize["new_city"] = o.NewCity
	}
	return toSerialize, nil
}

type NullableUpdateStreetDataAttributes struct {
	value *UpdateStreetDataAttributes
	isSet bool
}

func (v NullableUpdateStreetDataAttributes) Get() *UpdateStreetDataAttributes {
	return v.value
}

func (v *NullableUpdateStreetDataAttributes) Set(val *UpdateStreetDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStreetDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStreetDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStreetDataAttributes(val *UpdateStreetDataAttributes) *NullableUpdateStreetDataAttributes {
	return &NullableUpdateStreetDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateStreetDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStreetDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


