/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByCountry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByCountry{}

// DataByCountry struct for DataByCountry
type DataByCountry struct {
	Data DataByCountryData `json:"data"`
}

type _DataByCountry DataByCountry

// NewDataByCountry instantiates a new DataByCountry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByCountry(data DataByCountryData) *DataByCountry {
	this := DataByCountry{}
	this.Data = data
	return &this
}

// NewDataByCountryWithDefaults instantiates a new DataByCountry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByCountryWithDefaults() *DataByCountry {
	this := DataByCountry{}
	return &this
}

// GetData returns the Data field value
func (o *DataByCountry) GetData() DataByCountryData {
	if o == nil {
		var ret DataByCountryData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DataByCountry) GetDataOk() (*DataByCountryData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DataByCountry) SetData(v DataByCountryData) {
	o.Data = v
}

func (o DataByCountry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByCountry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DataByCountry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByCountry := _DataByCountry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByCountry)

	if err != nil {
		return err
	}

	*o = DataByCountry(varDataByCountry)

	return err
}

type NullableDataByCountry struct {
	value *DataByCountry
	isSet bool
}

func (v NullableDataByCountry) Get() *DataByCountry {
	return v.value
}

func (v *NullableDataByCountry) Set(val *DataByCountry) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByCountry(val *DataByCountry) *NullableDataByCountry {
	return &NullableDataByCountry{value: val, isSet: true}
}

func (v NullableDataByCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


