/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateStreet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStreet{}

// UpdateStreet struct for UpdateStreet
type UpdateStreet struct {
	Data UpdateStreetData `json:"data"`
}

type _UpdateStreet UpdateStreet

// NewUpdateStreet instantiates a new UpdateStreet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStreet(data UpdateStreetData) *UpdateStreet {
	this := UpdateStreet{}
	this.Data = data
	return &this
}

// NewUpdateStreetWithDefaults instantiates a new UpdateStreet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStreetWithDefaults() *UpdateStreet {
	this := UpdateStreet{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateStreet) GetData() UpdateStreetData {
	if o == nil {
		var ret UpdateStreetData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateStreet) GetDataOk() (*UpdateStreetData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateStreet) SetData(v UpdateStreetData) {
	o.Data = v
}

func (o UpdateStreet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStreet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateStreet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateStreet := _UpdateStreet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateStreet)

	if err != nil {
		return err
	}

	*o = UpdateStreet(varUpdateStreet)

	return err
}

type NullableUpdateStreet struct {
	value *UpdateStreet
	isSet bool
}

func (v NullableUpdateStreet) Get() *UpdateStreet {
	return v.value
}

func (v *NullableUpdateStreet) Set(val *UpdateStreet) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStreet) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStreet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStreet(val *UpdateStreet) *NullableUpdateStreet {
	return &NullableUpdateStreet{value: val, isSet: true}
}

func (v NullableUpdateStreet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStreet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


