/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByCityData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByCityData{}

// DataByCityData struct for DataByCityData
type DataByCityData struct {
	// city id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes DataByCityDataAttributes `json:"attributes"`
}

type _DataByCityData DataByCityData

// NewDataByCityData instantiates a new DataByCityData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByCityData(id string, type_ string, attributes DataByCityDataAttributes) *DataByCityData {
	this := DataByCityData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDataByCityDataWithDefaults instantiates a new DataByCityData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByCityDataWithDefaults() *DataByCityData {
	this := DataByCityData{}
	return &this
}

// GetId returns the Id field value
func (o *DataByCityData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataByCityData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataByCityData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DataByCityData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DataByCityData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DataByCityData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DataByCityData) GetAttributes() DataByCityDataAttributes {
	if o == nil {
		var ret DataByCityDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DataByCityData) GetAttributesOk() (*DataByCityDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DataByCityData) SetAttributes(v DataByCityDataAttributes) {
	o.Attributes = v
}

func (o DataByCityData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByCityData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DataByCityData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByCityData := _DataByCityData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByCityData)

	if err != nil {
		return err
	}

	*o = DataByCityData(varDataByCityData)

	return err
}

type NullableDataByCityData struct {
	value *DataByCityData
	isSet bool
}

func (v NullableDataByCityData) Get() *DataByCityData {
	return v.value
}

func (v *NullableDataByCityData) Set(val *DataByCityData) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByCityData) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByCityData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByCityData(val *DataByCityData) *NullableDataByCityData {
	return &NullableDataByCityData{value: val, isSet: true}
}

func (v NullableDataByCityData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByCityData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


