/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDistrict type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistrict{}

// UpdateDistrict struct for UpdateDistrict
type UpdateDistrict struct {
	Data UpdateDistrictData `json:"data"`
}

type _UpdateDistrict UpdateDistrict

// NewUpdateDistrict instantiates a new UpdateDistrict object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistrict(data UpdateDistrictData) *UpdateDistrict {
	this := UpdateDistrict{}
	this.Data = data
	return &this
}

// NewUpdateDistrictWithDefaults instantiates a new UpdateDistrict object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistrictWithDefaults() *UpdateDistrict {
	this := UpdateDistrict{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateDistrict) GetData() UpdateDistrictData {
	if o == nil {
		var ret UpdateDistrictData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateDistrict) GetDataOk() (*UpdateDistrictData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateDistrict) SetData(v UpdateDistrictData) {
	o.Data = v
}

func (o UpdateDistrict) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistrict) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateDistrict) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDistrict := _UpdateDistrict{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDistrict)

	if err != nil {
		return err
	}

	*o = UpdateDistrict(varUpdateDistrict)

	return err
}

type NullableUpdateDistrict struct {
	value *UpdateDistrict
	isSet bool
}

func (v NullableUpdateDistrict) Get() *UpdateDistrict {
	return v.value
}

func (v *NullableUpdateDistrict) Set(val *UpdateDistrict) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistrict) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistrict) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistrict(val *UpdateDistrict) *NullableUpdateDistrict {
	return &NullableUpdateDistrict{value: val, isSet: true}
}

func (v NullableUpdateDistrict) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistrict) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


