/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateCityDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCityDataAttributes{}

// UpdateCityDataAttributes struct for UpdateCityDataAttributes
type UpdateCityDataAttributes struct {
	// City new name
	NewName *string `json:"new_name,omitempty"`
	// City new location
	NewLocation *string `json:"new_location,omitempty"`
}

// NewUpdateCityDataAttributes instantiates a new UpdateCityDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCityDataAttributes() *UpdateCityDataAttributes {
	this := UpdateCityDataAttributes{}
	return &this
}

// NewUpdateCityDataAttributesWithDefaults instantiates a new UpdateCityDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCityDataAttributesWithDefaults() *UpdateCityDataAttributes {
	this := UpdateCityDataAttributes{}
	return &this
}

// GetNewName returns the NewName field value if set, zero value otherwise.
func (o *UpdateCityDataAttributes) GetNewName() string {
	if o == nil || IsNil(o.NewName) {
		var ret string
		return ret
	}
	return *o.NewName
}

// GetNewNameOk returns a tuple with the NewName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCityDataAttributes) GetNewNameOk() (*string, bool) {
	if o == nil || IsNil(o.NewName) {
		return nil, false
	}
	return o.NewName, true
}

// HasNewName returns a boolean if a field has been set.
func (o *UpdateCityDataAttributes) HasNewName() bool {
	if o != nil && !IsNil(o.NewName) {
		return true
	}

	return false
}

// SetNewName gets a reference to the given string and assigns it to the NewName field.
func (o *UpdateCityDataAttributes) SetNewName(v string) {
	o.NewName = &v
}

// GetNewLocation returns the NewLocation field value if set, zero value otherwise.
func (o *UpdateCityDataAttributes) GetNewLocation() string {
	if o == nil || IsNil(o.NewLocation) {
		var ret string
		return ret
	}
	return *o.NewLocation
}

// GetNewLocationOk returns a tuple with the NewLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCityDataAttributes) GetNewLocationOk() (*string, bool) {
	if o == nil || IsNil(o.NewLocation) {
		return nil, false
	}
	return o.NewLocation, true
}

// HasNewLocation returns a boolean if a field has been set.
func (o *UpdateCityDataAttributes) HasNewLocation() bool {
	if o != nil && !IsNil(o.NewLocation) {
		return true
	}

	return false
}

// SetNewLocation gets a reference to the given string and assigns it to the NewLocation field.
func (o *UpdateCityDataAttributes) SetNewLocation(v string) {
	o.NewLocation = &v
}

func (o UpdateCityDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCityDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NewName) {
		toSerialize["new_name"] = o.NewName
	}
	if !IsNil(o.NewLocation) {
		toSerialize["new_location"] = o.NewLocation
	}
	return toSerialize, nil
}

type NullableUpdateCityDataAttributes struct {
	value *UpdateCityDataAttributes
	isSet bool
}

func (v NullableUpdateCityDataAttributes) Get() *UpdateCityDataAttributes {
	return v.value
}

func (v *NullableUpdateCityDataAttributes) Set(val *UpdateCityDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCityDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCityDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCityDataAttributes(val *UpdateCityDataAttributes) *NullableUpdateCityDataAttributes {
	return &NullableUpdateCityDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCityDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCityDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


