/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataByCityDataAttributesDistrictsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataByCityDataAttributesDistrictsInner{}

// DataByCityDataAttributesDistrictsInner struct for DataByCityDataAttributesDistrictsInner
type DataByCityDataAttributesDistrictsInner struct {
	// district id
	Id string `json:"id"`
	// District name
	Name string `json:"name"`
}

type _DataByCityDataAttributesDistrictsInner DataByCityDataAttributesDistrictsInner

// NewDataByCityDataAttributesDistrictsInner instantiates a new DataByCityDataAttributesDistrictsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataByCityDataAttributesDistrictsInner(id string, name string) *DataByCityDataAttributesDistrictsInner {
	this := DataByCityDataAttributesDistrictsInner{}
	this.Id = id
	this.Name = name
	return &this
}

// NewDataByCityDataAttributesDistrictsInnerWithDefaults instantiates a new DataByCityDataAttributesDistrictsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataByCityDataAttributesDistrictsInnerWithDefaults() *DataByCityDataAttributesDistrictsInner {
	this := DataByCityDataAttributesDistrictsInner{}
	return &this
}

// GetId returns the Id field value
func (o *DataByCityDataAttributesDistrictsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributesDistrictsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DataByCityDataAttributesDistrictsInner) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DataByCityDataAttributesDistrictsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DataByCityDataAttributesDistrictsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DataByCityDataAttributesDistrictsInner) SetName(v string) {
	o.Name = v
}

func (o DataByCityDataAttributesDistrictsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataByCityDataAttributesDistrictsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *DataByCityDataAttributesDistrictsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataByCityDataAttributesDistrictsInner := _DataByCityDataAttributesDistrictsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataByCityDataAttributesDistrictsInner)

	if err != nil {
		return err
	}

	*o = DataByCityDataAttributesDistrictsInner(varDataByCityDataAttributesDistrictsInner)

	return err
}

type NullableDataByCityDataAttributesDistrictsInner struct {
	value *DataByCityDataAttributesDistrictsInner
	isSet bool
}

func (v NullableDataByCityDataAttributesDistrictsInner) Get() *DataByCityDataAttributesDistrictsInner {
	return v.value
}

func (v *NullableDataByCityDataAttributesDistrictsInner) Set(val *DataByCityDataAttributesDistrictsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataByCityDataAttributesDistrictsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataByCityDataAttributesDistrictsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataByCityDataAttributesDistrictsInner(val *DataByCityDataAttributesDistrictsInner) *NullableDataByCityDataAttributesDistrictsInner {
	return &NullableDataByCityDataAttributesDistrictsInner{value: val, isSet: true}
}

func (v NullableDataByCityDataAttributesDistrictsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataByCityDataAttributesDistrictsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


