/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCityData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCityData{}

// CreateCityData struct for CreateCityData
type CreateCityData struct {
	Type string `json:"type"`
	Attributes CreateCityDataAttributes `json:"attributes"`
}

type _CreateCityData CreateCityData

// NewCreateCityData instantiates a new CreateCityData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCityData(type_ string, attributes CreateCityDataAttributes) *CreateCityData {
	this := CreateCityData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateCityDataWithDefaults instantiates a new CreateCityData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCityDataWithDefaults() *CreateCityData {
	this := CreateCityData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateCityData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateCityData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateCityData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateCityData) GetAttributes() CreateCityDataAttributes {
	if o == nil {
		var ret CreateCityDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateCityData) GetAttributesOk() (*CreateCityDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateCityData) SetAttributes(v CreateCityDataAttributes) {
	o.Attributes = v
}

func (o CreateCityData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCityData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateCityData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCityData := _CreateCityData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCityData)

	if err != nil {
		return err
	}

	*o = CreateCityData(varCreateCityData)

	return err
}

type NullableCreateCityData struct {
	value *CreateCityData
	isSet bool
}

func (v NullableCreateCityData) Get() *CreateCityData {
	return v.value
}

func (v *NullableCreateCityData) Set(val *CreateCityData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCityData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCityData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCityData(val *CreateCityData) *NullableCreateCityData {
	return &NullableCreateCityData{value: val, isSet: true}
}

func (v NullableCreateCityData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCityData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


