// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbcore

import (
	"database/sql"

	"github.com/google/uuid"
)

type City struct {
	ID        uuid.UUID
	Name      sql.NullString
	CountryID sql.NullInt32
}

type Country struct {
	ID   uuid.UUID
	Name sql.NullString
}

type District struct {
	ID     uuid.UUID
	Name   string
	CityID sql.NullInt32
}

type Street struct {
	ID         uuid.UUID
	Name       string
	DistrictID int32
}
