// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbcore

import (
	"github.com/google/uuid"
)

type City struct {
	ID       uuid.UUID
	Name     string
	Location interface{}
}

type Street struct {
	ID       uuid.UUID
	Name     string
	CityID   uuid.UUID
	Location interface{}
}
