// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: streets.sql

package dbcore

import (
	"context"

	"github.com/google/uuid"
)

const createStreet = `-- name: CreateStreet :exec
INSERT INTO streets (name, district_id) VALUES ($1, $2)
`

type CreateStreetParams struct {
	Name       string
	DistrictID int32
}

func (q *Queries) CreateStreet(ctx context.Context, arg CreateStreetParams) error {
	_, err := q.db.ExecContext(ctx, createStreet, arg.Name, arg.DistrictID)
	return err
}

const deleteStreet = `-- name: DeleteStreet :exec
DELETE FROM streets WHERE id = $1
`

func (q *Queries) DeleteStreet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStreet, id)
	return err
}

const getStreetByID = `-- name: GetStreetByID :one
SELECT id, name, district_id FROM streets WHERE id = $1
`

func (q *Queries) GetStreetByID(ctx context.Context, id uuid.UUID) (Street, error) {
	row := q.db.QueryRowContext(ctx, getStreetByID, id)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}

const getStreetsByDistrict = `-- name: GetStreetsByDistrict :many
SELECT id, name FROM streets WHERE district_id = $1
`

type GetStreetsByDistrictRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetStreetsByDistrict(ctx context.Context, districtID int32) ([]GetStreetsByDistrictRow, error) {
	rows, err := q.db.QueryContext(ctx, getStreetsByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStreetsByDistrictRow
	for rows.Next() {
		var i GetStreetsByDistrictRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStreet = `-- name: UpdateStreet :exec
UPDATE streets SET name = $2, district_id = $3 WHERE id = $1
`

type UpdateStreetParams struct {
	ID         uuid.UUID
	Name       string
	DistrictID int32
}

func (q *Queries) UpdateStreet(ctx context.Context, arg UpdateStreetParams) error {
	_, err := q.db.ExecContext(ctx, updateStreet, arg.ID, arg.Name, arg.DistrictID)
	return err
}
