// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: streets.sql

package dbcore

import (
	"context"

	"github.com/google/uuid"
)

const createStreet = `-- name: CreateStreet :one
INSERT INTO streets (
    name,
    district_id
) VALUES (
    $1, $2
)  RETURNING id, name, district_id
`

type CreateStreetParams struct {
	Name       string
	DistrictID uuid.UUID
}

func (q *Queries) CreateStreet(ctx context.Context, arg CreateStreetParams) (Street, error) {
	row := q.db.QueryRowContext(ctx, createStreet, arg.Name, arg.DistrictID)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}

const deleteStreet = `-- name: DeleteStreet :exec
DELETE FROM streets WHERE id = $1
`

func (q *Queries) DeleteStreet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStreet, id)
	return err
}

const getStreetByID = `-- name: GetStreetByID :one
SELECT id, name, district_id FROM streets WHERE id = $1
`

func (q *Queries) GetStreetByID(ctx context.Context, id uuid.UUID) (Street, error) {
	row := q.db.QueryRowContext(ctx, getStreetByID, id)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}

const getStreetByName = `-- name: GetStreetByName :one
SELECT id, name, district_id FROM streets WHERE name = $1
`

func (q *Queries) GetStreetByName(ctx context.Context, name string) (Street, error) {
	row := q.db.QueryRowContext(ctx, getStreetByName, name)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}

const getStreetsByDistrict = `-- name: GetStreetsByDistrict :many
SELECT id, name, district_id FROM streets WHERE district_id = $1
`

func (q *Queries) GetStreetsByDistrict(ctx context.Context, districtID uuid.UUID) ([]Street, error) {
	rows, err := q.db.QueryContext(ctx, getStreetsByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Street
	for rows.Next() {
		var i Street
		if err := rows.Scan(&i.ID, &i.Name, &i.DistrictID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStreetDistrict = `-- name: UpdateStreetDistrict :one
UPDATE streets SET
   district_id = $2
WHERE
   id = $1
RETURNING id, name, district_id
`

type UpdateStreetDistrictParams struct {
	ID         uuid.UUID
	DistrictID uuid.UUID
}

func (q *Queries) UpdateStreetDistrict(ctx context.Context, arg UpdateStreetDistrictParams) (Street, error) {
	row := q.db.QueryRowContext(ctx, updateStreetDistrict, arg.ID, arg.DistrictID)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}

const updateStreetName = `-- name: UpdateStreetName :one
UPDATE streets SET
   name = $2
WHERE
   id = $1
RETURNING id, name, district_id
`

type UpdateStreetNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateStreetName(ctx context.Context, arg UpdateStreetNameParams) (Street, error) {
	row := q.db.QueryRowContext(ctx, updateStreetName, arg.ID, arg.Name)
	var i Street
	err := row.Scan(&i.ID, &i.Name, &i.DistrictID)
	return i, err
}
