openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /users/create:
    post:
      operationId: test
      responses:
        "201":
          description: test
      summary: test
components:
  schemas:
    Errors:
      description: Standard JSON:API error
      properties:
        errors:
          description: Non empty array of errors occurred during request processing
          items:
            $ref: '#/components/schemas/Errors_errors_inner'
          type: array
      required:
      - errors
      type: object
    CreateCity:
      properties:
        data:
          $ref: '#/components/schemas/CreateCity_data'
      required:
      - data
      type: object
    CreateStreet:
      properties:
        data:
          $ref: '#/components/schemas/CreateStreet_data'
      required:
      - data
      type: object
    UpdateCity:
      properties:
        data:
          $ref: '#/components/schemas/UpdateCity_data'
      required:
      - data
      type: object
    UpdateStreet:
      properties:
        data:
          $ref: '#/components/schemas/UpdateStreet_data'
      required:
      - data
      type: object
    DataByCity:
      properties:
        data:
          $ref: '#/components/schemas/DataByCity_data'
      required:
      - data
      type: object
    DataByStreet:
      properties:
        data:
          $ref: '#/components/schemas/DataByStreet_data'
      required:
      - data
      type: object
    Errors_errors_inner:
      properties:
        title:
          description: "Title is a short, human-readable summary of the problem"
          example: Bad Request
          type: string
        detail:
          description: Detail is a human-readable explanation specific to this occurrence
            of the problem
          example: Request body was expected
          type: string
        status:
          description: Status is the HTTP status code applicable to this problem
          enum:
          - 400
          - 401
          - 403
          - 404
          - 409
          - 500
          example: 400
          type: integer
      required:
      - status
      - title
      type: object
    CreateCity_data_attributes:
      properties:
        name:
          description: City name
          example: kyiv
          type: string
        location:
          description: City location
          example: "50.4501,30.5234"
          type: string
      required:
      - location
      - name
      type: object
    CreateCity_data:
      properties:
        type:
          enum:
          - create_city
          type: string
        attributes:
          $ref: '#/components/schemas/CreateCity_data_attributes'
      required:
      - attributes
      - type
      type: object
    CreateStreet_data_attributes:
      properties:
        name:
          description: city name
          example: Saltovksliy district
          type: string
        city_id:
          description: city uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          type: string
        location:
          description: Street location
          example: "50.4501,30.5234"
          type: string
      required:
      - city_id
      - location
      - name
      type: object
    CreateStreet_data:
      properties:
        type:
          enum:
          - create_street
          type: string
        attributes:
          $ref: '#/components/schemas/CreateStreet_data_attributes'
      required:
      - attributes
      - type
      type: object
    UpdateCity_data_attributes:
      properties:
        new_name:
          description: City new name
          example: kyiv
          type: string
        new_location:
          description: City new location
          example: "50.4501,30.5234"
          type: string
      type: object
    UpdateCity_data:
      properties:
        type:
          enum:
          - update_city
          type: string
        id:
          description: City uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateCity_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    UpdateStreet_data_attributes:
      properties:
        new_name:
          description: City name
          example: kyiv
          type: string
        new_location:
          description: City location
          example: "50.4501,30.5234"
          type: string
        new_city:
          description: City uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
          type: string
      type: object
    UpdateStreet_data:
      properties:
        id:
          description: street id
          format: uuid
          type: string
        type:
          enum:
          - update_street
          type: string
        attributes:
          $ref: '#/components/schemas/UpdateStreet_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    DataByCity_data_attributes_streets_inner:
      properties:
        id:
          description: street id
          format: uuid
          type: string
        name:
          description: street name
          type: string
        locations:
          description: street location
          type: string
      required:
      - id
      - locations
      - name
      type: object
    DataByCity_data_attributes:
      properties:
        name:
          description: City name
          type: string
        locations:
          description: City location
          example: "50.4501,30.5234"
          type: string
        streets:
          items:
            $ref: '#/components/schemas/DataByCity_data_attributes_streets_inner'
          type: array
      required:
      - locations
      - name
      - streets
      type: object
    DataByCity_data:
      properties:
        id:
          description: city id
          format: uuid
          type: string
        type:
          enum:
          - data_by_city
          type: string
        attributes:
          $ref: '#/components/schemas/DataByCity_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    DataByStreet_data_attributes:
      properties:
        city:
          description: city uuid
          type: string
        name:
          description: Street name
          type: string
        locations:
          description: Street location
          example: "50.4501,30.5234"
          type: string
      required:
      - city
      - locations
      - name
      type: object
    DataByStreet_data:
      properties:
        id:
          description: street id
          format: uuid
          type: string
        type:
          enum:
          - data_by_street
          type: string
        attributes:
          $ref: '#/components/schemas/DataByStreet_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
