openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /users/create:
    post:
      summary: test
      operationId: test
      responses:
        '201':
          description: test

components:
  schemas:
    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
    CreateCity:
      $ref: './spec/components/schemas/CreateCity.yaml'
    CreateStreet:
      $ref: './spec/components/schemas/CreateStreet.yaml'
    UpdateCity:
      $ref: './spec/components/schemas/UpdateCity.yaml'
    UpdateStreet:
      $ref: './spec/components/schemas/UpdateStreet.yaml'
    DataByCity:
      $ref: './spec/components/schemas/DataByCity.yaml'
    DataByStreet:
      $ref: './spec/components/schemas/DataByStreet.yaml'